# Generated by Django 3.1.4 on 2020-12-15 21:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("contentcuration", "0127_auto_20201215_1820"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="content_defaults",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="channel",
            name="published_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="channel",
            name="thumbnail_encoding",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="contentnode",
            name="extra_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="slideshowslide",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="task", name="metadata", field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="content_defaults",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user", name="information", field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="policies",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
